//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using testweb;
    
    public class _Page_Views_Shared_Error_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
#line hidden
        public _Page_Views_Shared_Error_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width\"");

WriteLiteral(" />\r\n    <title>Error</title>\r\n</head>\r\n<body>\r\n    <hgroup>\r\n        <h1>Error.<" +
"/h1>\r\n        <h2>An error occurred while processing your request.</h2>\r\n    </h" +
"group>\r\n</body>\r\n</html>\r\n");

        }
    }
}
